//Final JavaScript
const generateSleepyLink = function() {
    const sleepyzone = [
{ links: "<a href='https://soundcloud.com/blissom' target='_blank'>blissom", member: "<p> </p>" },
{ links: "<a href='https://www.youtube.com/watch?v=87_4nHEPHyU' target='_blank'>WORMS", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/coy-halverson' target='_blank'>coy", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/sc2un-sh4re' target='_blank'>sc2un sh4re", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/f1nley1' target='_blank'>f1nley", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/least_favorite' target='_blank'>leastfavorite!", member: "<p> </p>" },
{ links: "<a href='https://twitter.com/ftrskr_wav' target='_blank'>futureseeker", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/sh1bes' target='_blank'>shibes", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/01kon' target='_blank'>01kon", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/glarch' target='_blank'>glarch", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/mis4ortune' target='_blank'>mis4ortune", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/jane_lameee' target='_blank'>janeislameee", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/flexiimusic' target='_blank'>flexii", member: "<p> </p>" },
{ links: "<a href='https://www.instagram.com/1xcessgranted/' target='_blank'>accessgranted", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/keitrix' target='_blank'>Keitrix", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/burner-account-902853798' target='_blank'>Afraid of the Dark?", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/f1regek' target='_blank'>F1regek", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/nyancrimew' target='_blank'>nyancrimew", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/neverendingweekend' target='_blank'>neverending weekend", member: "<p> </p>" },
{ links: "<a href='https://twitter.com/CircuitRCAY' target='_blank'>CircuitRCAY", member: "<p> </p>" },
{ links: "<a href='https://twitter.com/xAlisonxMossx' target='_blank'>Alison Moss", member: "<p> </p>" },
{ links: "<a href='https://char.lt/' target='_blank'>charlotte", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/livewiress00' target='_blank'>livewiress", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/doteclipsis' target='_blank'>eclipsis", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/tetradecimalplusplus' target='_blank'>tetradecimal", member: "<p> </p>" },
{ links: "<a href='https://boxin.space' target='_blank'>mira", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/deguofficial' target='_blank'>degu.", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/ashsolaceatwillowmerepark' target='_blank'>ashtrxy_", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/tndiaalpffnjsp' target='_blank'>TNDiaALpFfNjsp", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/og_lost' target='_blank'>OG Lost", member: "<p> </p>" },
{ links: "<a href='https://twitter.com/Oliviaaaaaaaah' target='_blank'>olivia", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/alaskasargent' target='_blank'>Alaska Sargent", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/re_dd' target='_blank'>dfrost (aka gorb)", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/applemaggot' target='_blank'>applemaggot", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/vai5000' target='_blank'>vai5000", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/46b' target='_blank'>hexd", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/22hereknowswhen' target='_blank'>22hereknowswhen", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/gehooven' target='_blank'>BagelSasha", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/silicpn' target='_blank'>silicon'", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/lun_d' target='_blank'>Lundy", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/1flea' target='_blank'>fleafriends", member: "<p> </p>" },
{ links: "<a href='https://youtube.com/channel/UCFIQDkDbwEkNCDbVfkMNBdA' target='_blank'>SilentWuffer", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/gupsemicolon' target='_blank'>gupsemicolon", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/cherryrizla' target='_blank'>cherryrizla", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/garzibog' target='_blank'>garzibog", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/wood_lands' target='_blank'>wood_lands", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/elii4h' target='_blank'>eliiah2004", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/soundboimusic' target='_blank'>soundboi", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/violet-morgana' target='_blank'>violet morgana", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/hailstunes' target='_blank'>hailst", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/quedronol' target='_blank'>quedronol", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/mintymints7' target='_blank'>mintymints", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/noct_s' target='_blank'>noct!s", member: "<p> </p>" },
{ links: "<a href='https://caliconiko.tumblr.com/' target='_blank'>[caliconiko]", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/tayxm' target='_blank'>tayxm", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/jecoeur' target='_blank'>iheart", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/rhinozz' target='_blank'>Rhinozz", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/extrenordubs' target='_blank'>Extrenor", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/catdotflp' target='_blank'>cat.flp", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/bhproducer' target='_blank'>bh", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/dylazy' target='_blank'>dylazy", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/prodbyaustyn' target='_blank'>austyn with a y", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/jauntsen' target='_blank'>jauntsen !", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/anem0s' target='_blank'>anem0s", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/leytonmode' target='_blank'>leyton", member: "<p> </p>" },
{ links: "<a href='https://www.youtube.com/watch?v=1wnE4vF9CQ4' target='_blank'>rust", member: "<p> </p>" },
{ links: "<a href='https://www.mixcloud.com/elliot_v/' target='_blank'>nonbinaryboyfriend", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/nie-skowronek' target='_blank'>kole", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/panasonic-cat' target='_blank'>Carbonize", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/eli_xirs' target='_blank'>eli.xirs", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/eiburie' target='_blank'>eiburie", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/m_d_h' target='_blank'>Mattydee", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/micahcallari' target='_blank'>Micah Callari", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/madiserketarchive' target='_blank'>Madi Serket", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/user-231119318' target='_blank'>enkay", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/nxori' target='_blank'>initmd", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/apple-man-495106743' target='_blank'>Dawn of Apples", member: "<p> </p>" },
{ links: "<a href='https://soundcloud.com/faejr' target='_blank'>fae jr.", member: "<p> </p>" },
];

    let arrayIndex = Math.floor(Math.random() * sleepyzone.length);
    document.getElementById("sleepy").innerHTML = sleepyzone[arrayIndex].links;
    document.getElementById("member").innerHTML = sleepyzone[arrayIndex].member;

}
window.addEventListener ('load', function () {
    setInterval (generateSleepyLink, 2000);
}, false);
window.onload = function() {
    generateSleepyLink();
}
